package com.srct.service.dao.po;

public class Info {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column info.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column info.test_name
     * @mbg.generated
     */
    private String testName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column info.test_dispcription
     * @mbg.generated
     */
    private String testDispcription;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column info.id
     * @return  the value of info.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column info.id
     * @param id  the value for info.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column info.test_name
     * @return  the value of info.test_name
     * @mbg.generated
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column info.test_name
     * @param testName  the value for info.test_name
     * @mbg.generated
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column info.test_dispcription
     * @return  the value of info.test_dispcription
     * @mbg.generated
     */
    public String getTestDispcription() {
        return testDispcription;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column info.test_dispcription
     * @param testDispcription  the value for info.test_dispcription
     * @mbg.generated
     */
    public void setTestDispcription(String testDispcription) {
        this.testDispcription = testDispcription == null ? null : testDispcription.trim();
    }
}