DROP TABLE IF EXISTS `TABLE_NAME`;
CREATE TABLE IF NOT EXISTS `TABLE_NAME`
(
  `id`        INT(10) UNSIGNED    NOT NULL AUTO_INCREMENT,
  `title`     VARCHAR(50)         NULL     DEFAULT NULL COMMENT '角色名称',
  `comment`   VARCHAR(200)        NULL     DEFAULT NULL COMMENT '角色备注',
  `user_id`   INT(10) UNSIGNED    NULL     DEFAULT NULL COMMENT '人员信息',
  `start_at`  TIMESTAMP(3)        NULL     DEFAULT NULL COMMENT '有效期起始',
  `end_at`    TIMESTAMP(3)        NULL     DEFAULT NULL COMMENT '有效期结束',
  `create_at` TIMESTAMP(3)        NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_at` TIMESTAMP(3)        NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后修改时间',
  `last_at`   TIMESTAMP(3)        NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最后登入时间',
  `valid`     TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '有效性',
  PRIMARY KEY (`id`)
)
  COMMENT ='备注信息'
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB
;
